name: My-Github-Action-Telegram-Notification

on:
  push:
    branches: 
      - master
jobs:
  starting-job:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Print MESSAGE STARTING JOB
      run: echo "Произведен PUSH в MASTER"
    - name: Print all files
      run: ls -la
    - name: Sending PUSH in Telegram
      run: java -DconfigFile=telegram_config.json -jar allure-notifications-4.2.1.jar
      
