name: My-Github-Action-Telegram-Notification

on:
  push:
    branches: 
      - master
jobs:

  sending-notification-job:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Install allure
        run : npm install -g allure-commandline --save-dev
          
      - name: Run tests and generate results
        run : pytest -s -v --alluredir=allure-results
        
      - name: Generate allure reports
        run : allure generate --clean allure-results -o allure-report
        
      - name: Generate telegram configuration file
        id  : create-json 
        uses: jsdaniell/create-json@1.1.2 
        with: 
          name: "telegram_config.json" json: ${{ secrets.TELEGRAM_CONFIG_JSON }}
        
      - name: Send push-notification in Telegram
        run : java -DconfigFile=telegram_config.json -jar allure-notifications-4.2.1.jar
