name: My-Github-Action-telegram-notification
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    branches: 
      - master
jobs:
  starting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print MESSAGE STARTING JOB
      - run: echo "Произведен PUSH в MASTER"
      
